version: '3.8'

services:
  webapp:
    image: ivansher/randomizer-app:latest
    build: ./app
    volumes:
      - uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=334ersd
    networks:
      - app-network

  nginx:
    image: ivansher/randomizer-nginx:latest
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/nginx/ssl
      - uploads:/app/uploads
    depends_on:
      - webapp
    networks:
      - app-network

volumes:
  certbot-etc:
  uploads:

networks:
  app-network:
    driver: bridge